name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    env:
      CGO_ENABLED: 0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Download Go modules
        run: go mod download

      - name: Set environment variables
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          echo "COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "BUILD_TIME=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV
          echo "GO_VERSION=$(go version | awk '{print $3}')" >> $GITHUB_ENV

      - name: Build binary
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build \
            -trimpath \
            -ldflags="-s -w \
              -X 'main.Version=${{ env.VERSION }}' \
              -X 'main.GoVersion=${{ env.GO_VERSION }}' \
              -X 'main.Branch=${{ env.BRANCH }}' \
              -X 'main.Commit=${{ env.COMMIT }}' \
              -X 'main.BuildTime=${{ env.BUILD_TIME }}'" \
            -o dist/kubectl-watch-${{ matrix.goos }}-${{ matrix.goarch }} ./main.go

      - name: Generate checksums
        run: |
          cd dist
          shasum -a 256 * > checksums.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kubectl-watch-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/kubectl-watch-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload checksums (only once)
        if: matrix.goos == 'linux' && matrix.goarch == 'amd64'
        uses: actions/upload-artifact@v4
        with:
          name: checksums
          path: dist/checksums.txt

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download linux/amd64 binary
        uses: actions/download-artifact@v4
        with:
          name: kubectl-watch-linux-amd64
          path: dist/

      - name: Download linux/arm64 binary
        uses: actions/download-artifact@v4
        with:
          name: kubectl-watch-linux-arm64
          path: dist/

      - name: Download darwin/amd64 binary
        uses: actions/download-artifact@v4
        with:
          name: kubectl-watch-darwin-amd64
          path: dist/

      - name: Download darwin/arm64 binary
        uses: actions/download-artifact@v4
        with:
          name: kubectl-watch-darwin-arm64
          path: dist/

      - name: Download checksums
        uses: actions/download-artifact@v4
        with:
          name: checksums
          path: dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          draft: false
          files: |
            dist/kubectl-watch-*
            dist/checksums.txt
